```yaml
name: Terraform Dev Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_WORKING_DIR: environments/dev

jobs:

  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    # 3. Setup TFLint
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.50.3

    # 4. Initialize TFLint
    - name: Initialize TFLint
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: tflint --init

    # 5. Run TFLint
    - name: Run TFLint
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: tflint -f compact

    # 6. Run TFSec
    - name: Run TFSec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{ env.TF_WORKING_DIR }}
        soft_fail: true

    # 7. Terraform Init
    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    # 8. Terraform Validate
    - name: Terraform Validate
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform validate

    # 9. Terraform Plan
    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -no-color

    # 10. Terraform Apply
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform
```
